all: false
formatter: goimports
template: testify
filename: "mocks.go"
dir: "{{.InterfaceDir}}"
pkgname: "{{.SrcPackageName}}mocks"
structname: "{{.Mock}}{{.InterfaceName}}"
recursive: false

packages:
  github.com/shrtyk/subscriptions-service/internal/core/ports:
    config:
      recursive: true
      all: true
      dir: "{{.InterfaceDir}}/mocks"
