// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package txmocks

import (
	"context"

	"github.com/shrtyk/subscriptions-service/internal/core/ports/repos"
	"github.com/shrtyk/subscriptions-service/internal/core/ports/tx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Subscriptions provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Subscriptions() repos.SubscriptionRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscriptions")
	}

	var r0 repos.SubscriptionRepository
	if returnFunc, ok := ret.Get(0).(func() repos.SubscriptionRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repos.SubscriptionRepository)
		}
	}
	return r0
}

// MockUnitOfWork_Subscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscriptions'
type MockUnitOfWork_Subscriptions_Call struct {
	*mock.Call
}

// Subscriptions is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Subscriptions() *MockUnitOfWork_Subscriptions_Call {
	return &MockUnitOfWork_Subscriptions_Call{Call: _e.mock.On("Subscriptions")}
}

func (_c *MockUnitOfWork_Subscriptions_Call) Run(run func()) *MockUnitOfWork_Subscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Subscriptions_Call) Return(subscriptionRepository repos.SubscriptionRepository) *MockUnitOfWork_Subscriptions_Call {
	_c.Call.Return(subscriptionRepository)
	return _c
}

func (_c *MockUnitOfWork_Subscriptions_Call) RunAndReturn(run func() repos.SubscriptionRepository) *MockUnitOfWork_Subscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function for the type MockProvider
func (_mock *MockProvider) WithTransaction(ctx context.Context, fn func(uow tx.UnitOfWork) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(uow tx.UnitOfWork) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockProvider_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(uow tx.UnitOfWork) error
func (_e *MockProvider_Expecter) WithTransaction(ctx interface{}, fn interface{}) *MockProvider_WithTransaction_Call {
	return &MockProvider_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockProvider_WithTransaction_Call) Run(run func(ctx context.Context, fn func(uow tx.UnitOfWork) error)) *MockProvider_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(uow tx.UnitOfWork) error
		if args[1] != nil {
			arg1 = args[1].(func(uow tx.UnitOfWork) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_WithTransaction_Call) Return(err error) *MockProvider_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(uow tx.UnitOfWork) error) error) *MockProvider_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
