// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subservicemocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shrtyk/subscriptions-service/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionsService creates a new instance of MockSubscriptionsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionsService {
	mock := &MockSubscriptionsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionsService is an autogenerated mock type for the SubscriptionsService type
type MockSubscriptionsService struct {
	mock.Mock
}

type MockSubscriptionsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionsService) EXPECT() *MockSubscriptionsService_Expecter {
	return &MockSubscriptionsService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSubscriptionsService
func (_mock *MockSubscriptionsService) Create(ctx context.Context, sub domain.Subscription) (*domain.Subscription, error) {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Subscription) (*domain.Subscription, error)); ok {
		return returnFunc(ctx, sub)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Subscription) *domain.Subscription); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Subscription) error); ok {
		r1 = returnFunc(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionsService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sub domain.Subscription
func (_e *MockSubscriptionsService_Expecter) Create(ctx interface{}, sub interface{}) *MockSubscriptionsService_Create_Call {
	return &MockSubscriptionsService_Create_Call{Call: _e.mock.On("Create", ctx, sub)}
}

func (_c *MockSubscriptionsService_Create_Call) Run(run func(ctx context.Context, sub domain.Subscription)) *MockSubscriptionsService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Subscription
		if args[1] != nil {
			arg1 = args[1].(domain.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionsService_Create_Call) Return(subscription *domain.Subscription, err error) *MockSubscriptionsService_Create_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionsService_Create_Call) RunAndReturn(run func(ctx context.Context, sub domain.Subscription) (*domain.Subscription, error)) *MockSubscriptionsService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSubscriptionsService
func (_mock *MockSubscriptionsService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionsService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubscriptionsService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionsService_Expecter) Delete(ctx interface{}, id interface{}) *MockSubscriptionsService_Delete_Call {
	return &MockSubscriptionsService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSubscriptionsService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionsService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionsService_Delete_Call) Return(err error) *MockSubscriptionsService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionsService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSubscriptionsService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSubscriptionsService
func (_mock *MockSubscriptionsService) GetByID(ctx context.Context, id uuid.UUID) (*domain.Subscription, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Subscription, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Subscription); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubscriptionsService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionsService_Expecter) GetByID(ctx interface{}, id interface{}) *MockSubscriptionsService_GetByID_Call {
	return &MockSubscriptionsService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSubscriptionsService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionsService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionsService_GetByID_Call) Return(subscription *domain.Subscription, err error) *MockSubscriptionsService_GetByID_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionsService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Subscription, error)) *MockSubscriptionsService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSubscriptionsService
func (_mock *MockSubscriptionsService) List(ctx context.Context, filter domain.SubscriptionFilter) ([]domain.Subscription, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SubscriptionFilter) ([]domain.Subscription, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SubscriptionFilter) []domain.Subscription); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SubscriptionFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubscriptionsService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.SubscriptionFilter
func (_e *MockSubscriptionsService_Expecter) List(ctx interface{}, filter interface{}) *MockSubscriptionsService_List_Call {
	return &MockSubscriptionsService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockSubscriptionsService_List_Call) Run(run func(ctx context.Context, filter domain.SubscriptionFilter)) *MockSubscriptionsService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SubscriptionFilter
		if args[1] != nil {
			arg1 = args[1].(domain.SubscriptionFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionsService_List_Call) Return(subscriptions []domain.Subscription, err error) *MockSubscriptionsService_List_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockSubscriptionsService_List_Call) RunAndReturn(run func(ctx context.Context, filter domain.SubscriptionFilter) ([]domain.Subscription, error)) *MockSubscriptionsService_List_Call {
	_c.Call.Return(run)
	return _c
}

// TotalCost provides a mock function for the type MockSubscriptionsService
func (_mock *MockSubscriptionsService) TotalCost(ctx context.Context, filter domain.SubscriptionFilter, start time.Time, end time.Time) (int, error) {
	ret := _mock.Called(ctx, filter, start, end)

	if len(ret) == 0 {
		panic("no return value specified for TotalCost")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SubscriptionFilter, time.Time, time.Time) (int, error)); ok {
		return returnFunc(ctx, filter, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SubscriptionFilter, time.Time, time.Time) int); ok {
		r0 = returnFunc(ctx, filter, start, end)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SubscriptionFilter, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, filter, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsService_TotalCost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalCost'
type MockSubscriptionsService_TotalCost_Call struct {
	*mock.Call
}

// TotalCost is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.SubscriptionFilter
//   - start time.Time
//   - end time.Time
func (_e *MockSubscriptionsService_Expecter) TotalCost(ctx interface{}, filter interface{}, start interface{}, end interface{}) *MockSubscriptionsService_TotalCost_Call {
	return &MockSubscriptionsService_TotalCost_Call{Call: _e.mock.On("TotalCost", ctx, filter, start, end)}
}

func (_c *MockSubscriptionsService_TotalCost_Call) Run(run func(ctx context.Context, filter domain.SubscriptionFilter, start time.Time, end time.Time)) *MockSubscriptionsService_TotalCost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SubscriptionFilter
		if args[1] != nil {
			arg1 = args[1].(domain.SubscriptionFilter)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubscriptionsService_TotalCost_Call) Return(n int, err error) *MockSubscriptionsService_TotalCost_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubscriptionsService_TotalCost_Call) RunAndReturn(run func(ctx context.Context, filter domain.SubscriptionFilter, start time.Time, end time.Time) (int, error)) *MockSubscriptionsService_TotalCost_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSubscriptionsService
func (_mock *MockSubscriptionsService) Update(ctx context.Context, sub domain.Subscription) (*domain.Subscription, error) {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Subscription) (*domain.Subscription, error)); ok {
		return returnFunc(ctx, sub)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Subscription) *domain.Subscription); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Subscription) error); ok {
		r1 = returnFunc(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionsService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionsService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sub domain.Subscription
func (_e *MockSubscriptionsService_Expecter) Update(ctx interface{}, sub interface{}) *MockSubscriptionsService_Update_Call {
	return &MockSubscriptionsService_Update_Call{Call: _e.mock.On("Update", ctx, sub)}
}

func (_c *MockSubscriptionsService_Update_Call) Run(run func(ctx context.Context, sub domain.Subscription)) *MockSubscriptionsService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Subscription
		if args[1] != nil {
			arg1 = args[1].(domain.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionsService_Update_Call) Return(subscription *domain.Subscription, err error) *MockSubscriptionsService_Update_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionsService_Update_Call) RunAndReturn(run func(ctx context.Context, sub domain.Subscription) (*domain.Subscription, error)) *MockSubscriptionsService_Update_Call {
	_c.Call.Return(run)
	return _c
}
