// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewSubscription defines model for NewSubscription.
type NewSubscription struct {
	// EndDate End month and year (MM-YYYY)
	EndDate     *string `json:"end_date,omitempty"`
	MonthlyCost float32 `json:"monthly_cost"`
	ServiceName string  `json:"service_name"`

	// StartDate Start month and year (MM-YYYY)
	StartDate string             `json:"start_date"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	// EndDate Subscription end date (MM-YYYY), optional.
	EndDate *string `json:"end_date"`

	// Id Unique identifier for the subscription.
	Id openapi_types.UUID `json:"id"`

	// MonthlyCost Monthly cost in rubles.
	MonthlyCost float32 `json:"monthly_cost"`

	// ServiceName Name of the service.
	ServiceName string `json:"service_name"`

	// StartDate Subscription start date (MM-YYYY).
	StartDate string `json:"start_date"`

	// UserId ID of the user.
	UserId openapi_types.UUID `json:"user_id"`
}

// ListSubscriptionsParams defines parameters for ListSubscriptions.
type ListSubscriptionsParams struct {
	// UserId Filter by user ID
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`

	// ServiceName Filter by service name
	ServiceName *string `form:"service_name,omitempty" json:"service_name,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetTotalCostParams defines parameters for GetTotalCost.
type GetTotalCostParams struct {
	// UserId ID of the user
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`

	// ServiceName Name of the service
	ServiceName *string `form:"service_name,omitempty" json:"service_name,omitempty"`

	// Start Start of the period (MM-YYYY)
	Start *string `form:"start,omitempty" json:"start,omitempty"`

	// End End of the period (MM-YYYY)
	End *string `form:"end,omitempty" json:"end,omitempty"`
}

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = NewSubscription

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = NewSubscription
