// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reposmocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/shrtyk/subscriptions-service/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Create(ctx context.Context, sub *domain.Subscription) error {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Subscription) error); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *domain.Subscription
func (_e *MockSubscriptionRepository_Expecter) Create(ctx interface{}, sub interface{}) *MockSubscriptionRepository_Create_Call {
	return &MockSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, sub)}
}

func (_c *MockSubscriptionRepository_Create_Call) Run(run func(ctx context.Context, sub *domain.Subscription)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Subscription
		if args[1] != nil {
			arg1 = args[1].(*domain.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) Return(err error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, sub *domain.Subscription) error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSubscriptionRepository_Delete_Call {
	return &MockSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSubscriptionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) Return(err error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Subscription, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Subscription, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Subscription); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubscriptionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubscriptionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSubscriptionRepository_GetByID_Call {
	return &MockSubscriptionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSubscriptionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) Return(subscription *domain.Subscription, err error) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Subscription, error)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) List(ctx context.Context, filter domain.SubscriptionFilter) ([]domain.Subscription, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SubscriptionFilter) ([]domain.Subscription, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SubscriptionFilter) []domain.Subscription); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SubscriptionFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubscriptionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.SubscriptionFilter
func (_e *MockSubscriptionRepository_Expecter) List(ctx interface{}, filter interface{}) *MockSubscriptionRepository_List_Call {
	return &MockSubscriptionRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockSubscriptionRepository_List_Call) Run(run func(ctx context.Context, filter domain.SubscriptionFilter)) *MockSubscriptionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SubscriptionFilter
		if args[1] != nil {
			arg1 = args[1].(domain.SubscriptionFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_List_Call) Return(subscriptions []domain.Subscription, err error) *MockSubscriptionRepository_List_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockSubscriptionRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter domain.SubscriptionFilter) ([]domain.Subscription, error)) *MockSubscriptionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Update(ctx context.Context, sub *domain.Subscription) error {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Subscription) error); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *domain.Subscription
func (_e *MockSubscriptionRepository_Expecter) Update(ctx interface{}, sub interface{}) *MockSubscriptionRepository_Update_Call {
	return &MockSubscriptionRepository_Update_Call{Call: _e.mock.On("Update", ctx, sub)}
}

func (_c *MockSubscriptionRepository_Update_Call) Run(run func(ctx context.Context, sub *domain.Subscription)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Subscription
		if args[1] != nil {
			arg1 = args[1].(*domain.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) Return(err error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, sub *domain.Subscription) error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
